"""Add created_at column to User model

Revision ID: 2b5227bf6992
Revises: 
Create Date: 2025-05-10 18:26:22.669216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5227bf6992'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute('UPDATE user SET created_at = CURRENT_TIMESTAMP')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
    # ### end Alembic commands ###
