"""empty message

Revision ID: 902eae9819e7
Revises: 6f1698f97d35
Create Date: 2025-06-03 11:53:10.102633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902eae9819e7'
down_revision = '6f1698f97d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_layout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('layout_config', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('page_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta_description', sa.String(length=300), nullable=True),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['layout_id'], ['page_layout.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_name')
    )
    op.create_table('page_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('style_config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_section')
    op.drop_table('page_content')
    op.drop_table('page_layout')
    # ### end Alembic commands ###
